apiVersion: apps/v1
kind: Deployment
metadata:
  name: musinsa-app
spec:
  selector:
    matchLabels:
      app: musinsa-app
  replicas: 1
  template:
    metadata:
      labels:
        app: musinsa-app
    spec:
      containers:
        - name: musinsa-app
          image: dotoryeee/musinsa:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: AWS_ACCESS_KEY_ID
              value:
            - name: AWS_SECRET_ACCESS_KEY
              value:
            - name: AWS_DEFAULT_REGION
              value: ap-northeast-2
