apiVersion: v1
kind: Service
metadata:
  name: musinsa-service
  labels:
    app: musinsa-app
spec:
  type: NodePort
  selector:
    app: musinsa-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31333
